language: java
distro: focal
#virt: lxd #optional

matrix:
  include:
    - os: linux
      arch: arm64
      jdk: openjdk11
    - os: linux
      arch: s390x
      jdk: openjdk11
      addons:
        apt:
          update: true
          packages:
            - maven
            - libcppunit-dev

cache:
  directories:
  - "$HOME/.m2"

# addons:
#   apt:
#     packages:
#     - libcppunit-dev

install:
  - if [ "${TRAVIS_CPU_ARCH}" == "arm64" ]; then
     sudo apt-get install maven;
    fi

script: echo "This is a sample build"

branches:
  only:
  - main
